version: '3.8'

services:
  nginx:
    # When updating, always use mainline branch, that's what nginx recommends!
    image: nginx:1.19.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    networks:
      - frontend
    # disable noisy nginx logging :)
    logging:
      driver: "none"
  client:
    build: ./client
    restart: unless-stopped
    volumes:
      - ./client/:/home/node/app
      - next:/home/node/app/.next
      - node_modules_client:/home/node/app/node_modules
    networks:
      - frontend
    command: ./wait-for.sh server:8080 -- npm run dev
  server:
    build:
      context: ./server
      args:
        - NODE_ENV=development
    restart: unless-stopped
    environment:
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_PORT=27017
      - MONGO_DB=2DWebGame
      - MONGO_HOSTNAME=db
      - SPACES_KEY=$SPACES_KEY
      - SPACES_SECRET=$SPACES_SECRET
      - SPACES_FOLDER=$SPACES_FOLDER
      - SECURE_COOKIE=$SECURE_COOKIE
      - HASHIDS_PIC_SALT=$HASHIDS_PIC_SALT
      - HCAPTCHA_SECRET=$HCAPTCHA_SECRET
    volumes:
      - ./server/:/home/node/app
      - node_modules_server:/home/node/app/node_modules
    networks:
      - frontend
      - backend
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon main.js
  db:
    # Not using alpine, so I can reuse the image generated by the cluster when deploying locally
    image: mongo:4.4.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - dbdata:/data/db
      # Even though I'm not using this volume I'm still mounting it to a specific name
      # so no new random local volumes are being created every time I use compose
      - configdbdata:/data/configdb
    networks:
      - backend

volumes:
  next:
  node_modules_client:
  node_modules_server:
  dbdata:
  configdbdata:

networks:
  backend:
  frontend: